<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.0.2 (Python 3.8.10 on win32)" generated="20230202 18:50:43.059" rpa="false" schemaversion="3">
<suite id="s1" name="Test" source="C:\Users\Karin\Documents\Git-Source\Docker-Test\automate\test.robot">
<test id="s1-t1" name="Test_1_001" line="17">
<kw name="Open Application" library="AppiumLibrary">
<arg>remote_url=${CAPACIBILITY}[url]</arg>
<arg>platformName=${CAPACIBILITY}[platformName]</arg>
<arg>platformVersion=${CAPACIBILITY}[platformVersion]</arg>
<arg>deviceName=${CAPACIBILITY}[deviceName]</arg>
<arg>appPackage=${CAPACIBILITY}[appPackage]</arg>
<arg>appActivity=${CAPACIBILITY}[appActivity]</arg>
<arg>noReset=${True}</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |</doc>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20230202 18:51:04.257" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20230202 18:51:04.256" endtime="20230202 18:51:04.272"/>
</kw>
<msg timestamp="20230202 18:51:04.274" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20230202 18:51:04.275" level="FAIL">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20004ms.
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20004ms.
    at getResponseForW3CError (/usr/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
    at asyncHandler (/usr/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:380:37)</msg>
<status status="FAIL" starttime="20230202 18:50:43.523" endtime="20230202 18:51:04.276"/>
</kw>
<doc>Test
//c//Users//Karin//Documents//Git-Source//Docker-Test//automate://automate
//c//Users//Karin//Documents//Git-Source//Docker-Test//Result://Result</doc>
<status status="FAIL" starttime="20230202 18:50:43.522" endtime="20230202 18:51:04.277">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20004ms.
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not find a connected Android device in 20004ms.
    at getResponseForW3CError (/usr/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)
    at asyncHandler (/usr/lib/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:380:37)</status>
</test>
<doc>Test</doc>
<status status="FAIL" starttime="20230202 18:50:43.064" endtime="20230202 18:51:04.280"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Test">Test</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20230202 18:51:04.274" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
</errors>
</robot>
